---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  require_chef: false
  formula: hazelcast
  state_top:
    base:
      '*':
        - hazelcast

platforms:
  - name: ubuntu-xenial
    driver_config:
      run_command: /sbin/init

suites:
  - name: default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - hazelcast
        hazelcast.sls:
          hazelcast:
            home: /opt/
            version: '3.8.2'
            pkg_url: http://download.hazelcast.com/download.jsp?version=hazelcast-3.8.2&type=tar&p=
            pkg_hash: 'md5=d41d8cd98f00b204e9800998ecf8427e'
            name: 'hazelcast'
            password: NQmdgfeYYq1FfSQWR6
            management_url: 'http://localhost:8080/mancenter'
            port: 5701
            user: hazelcast
            group: hazelcast
            use_supervisor: false

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE