---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  require_chef: false
  formula: hazelcast
  state_top:
    base:
      '*':
        - hazelcast

platforms:
  - name: ubuntu-xenial
    driver_config:
      run_command: /sbin/init

suites:
  - name: default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - hazelcast
        hazelcast.sls:
          hazelcast:
            home: /opt/
            version: '3.8.3'
            # packages are not from official source
            pkg_url: http://download.openpkg.org/components/cache/hazelcast/hazelcast-3.8.3.tar.gz
            pkg_hash: 'md5=d199bb68b2191efb005ba52446d10278'
            name: 'hazelcast'
            password: NQmdgfeYYq1FfSQWR6
            management_url: 'http://localhost:8080/mancenter'
            port: 5701
            user: hazelcast
            group: hazelcast
            use_supervisor: false

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE