sudo: required

language: rvm

jdk: oraclejdk8

dist: trusty

services:
  - docker

before_install:
  - docker pull saltstack/ubuntu-14.04
  - pip install -r requirements.txt

script: bundle exec kitchen verify